name: Peterbuhlmann
favicon: null
layout_spectrum: 0.8606720387469977
typography_spectrum: 0.028305649291723967
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5769191726576537
  lightness: 0.5922557667363435
  saturation: 0.5098514552228153
  rhythmicContrast: 0.6127401504199952
purpose: []
