name: Peterbuhlmann
favicon: null
layout_spectrum: 0.12152
typography_spectrum: 0.49149
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c1c1a'
    - '#ffffff'
    - '#a2a4a3'
    - '#737675'
    - '#6d3d66'
  brandStrength: 0.5769191726576537
  lightness: 0.5922557667363435
  saturation: 0.5098514552228153
  rhythmicContrast: 0.6127401504199952
purpose: []
