name: Peterbuhlmann
favicon: null
layout_spectrum: 0.58447
typography_spectrum: 0.49149
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d99f33'
    - '#1d1610'
    - '#c6bebb'
    - '#9d4b2e'
    - '#d12921'
  brandStrength: 0.5769191726576537
  lightness: 0.5922557667363435
  saturation: 0.5
  rhythmicContrast: 0.6127401504199952
purpose: []
